// Code generated by ddtrace. DO NOT EDIT.
// source: example.go
// ddtrace: http://github.com/tyson-tuanvm/ddtrace

package trace

//go:generate ddtrace gen -p github.com/tuanvm-tyson/ddtrace/examples -o ./trace

import (
	"context"

	_sourceExamples "github.com/tuanvm-tyson/ddtrace/examples"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace"
	"gopkg.in/DataDog/dd-trace-go.v1/ddtrace/tracer"
)

// SpeakWithTracing implements Speak interface instrumented with Datadog tracing
type SpeakWithTracing struct {
	_sourceExamples.Speak
	_spanDecorator func(span ddtrace.Span, params, results map[string]interface{})
}

// NewSpeakWithTracing returns SpeakWithTracing
func NewSpeakWithTracing(base _sourceExamples.Speak, instance string, spanDecorator ...func(span ddtrace.Span, params, results map[string]interface{})) SpeakWithTracing {
	d := SpeakWithTracing{
		Speak: base,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// SayHello implements Speak
func (_d SpeakWithTracing) SayHello(ctx context.Context, name string) (s1 string) {
	span, ctx := tracer.StartSpanFromContext(ctx, "Speak.SayHello")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(span, map[string]interface{}{
				"ctx":  ctx,
				"name": name}, map[string]interface{}{
				"s1": s1})
		}
		span.Finish()
	}()
	return _d.Speak.SayHello(ctx, name)
}

type MoveWithTracing struct {
	_sourceExamples.Move
	_spanDecorator func(span ddtrace.Span, params, results map[string]interface{})
}

// NewMoveWithTracing returns MoveWithTracing
func NewMoveWithTracing(base _sourceExamples.Move, instance string, spanDecorator ...func(span ddtrace.Span, params, results map[string]interface{})) MoveWithTracing {
	d := MoveWithTracing{
		Move: base,
	}

	if len(spanDecorator) > 0 && spanDecorator[0] != nil {
		d._spanDecorator = spanDecorator[0]
	}

	return d
}

// Walk implements Move
func (_d MoveWithTracing) Walk(ctx context.Context, distance int) (s1 string) {
	span, ctx := tracer.StartSpanFromContext(ctx, "Move.Walk")
	defer func() {
		if _d._spanDecorator != nil {
			_d._spanDecorator(span, map[string]interface{}{
				"ctx":      ctx,
				"distance": distance}, map[string]interface{}{
				"s1": s1})
		}
		span.Finish()
	}()
	return _d.Move.Walk(ctx, distance)
}
