// Code generated by ddtrace. DO NOT EDIT.
// source: plain.go
// ddtrace: http://github.com/moneyforward/ddtrace

package trace

import (
	"context"

	_sourceExamples "github.com/moneyforward/ddtrace/examples"
	"github.com/moneyforward/ddtrace/tracing"
)

// FlyWithTracing implements Fly interface instrumented with Datadog tracing
type FlyWithTracing struct {
	_sourceExamples.Fly
	_cfg tracing.TracingConfig
}

// NewFlyWithTracing returns FlyWithTracing
func NewFlyWithTracing(base _sourceExamples.Fly, opts ...tracing.TracingOption) FlyWithTracing {
	return FlyWithTracing{
		Fly:  base,
		_cfg: tracing.NewTracingConfig(opts...),
	}
}

// SayHello implements Fly
func (_d FlyWithTracing) SayHello(ctx context.Context) (s1 string) {
	span, ctx := _d._cfg.StartSpan(ctx, "Fly.SayHello")
	defer func() {
		_d._cfg.FinishSpan(span, nil, map[string]interface{}{
			"ctx": ctx}, map[string]interface{}{
			"s1": s1})
	}()
	return _d.Fly.SayHello(ctx)
}
