// Code generated by ddtrace. DO NOT EDIT.
// source: example.go
// ddtrace: http://github.com/tuanvm-tyson/ddtrace

package trace

import (
	"context"

	_sourceGlobal "github.com/tuanvm-tyson/ddtrace/examples/global"
	"github.com/tuanvm-tyson/ddtrace/tracing"
)

// SpeakWithTracing implements Speak interface instrumented with Datadog tracing
type SpeakWithTracing struct {
	_sourceGlobal.Speak
	_cfg tracing.TracingConfig
}

// NewSpeakWithTracing returns SpeakWithTracing
func NewSpeakWithTracing(base _sourceGlobal.Speak, opts ...tracing.TracingOption) SpeakWithTracing {
	return SpeakWithTracing{
		Speak: base,
		_cfg:  tracing.NewTracingConfig(opts...),
	}
}

// SayHello implements Speak
func (_d SpeakWithTracing) SayHello(ctx context.Context, name string) (s1 string) {
	span, ctx := _d._cfg.StartSpan(ctx, "Speak.SayHello")
	defer func() {
		_d._cfg.FinishSpan(span, nil, map[string]interface{}{
			"ctx":  ctx,
			"name": name}, map[string]interface{}{
			"s1": s1})
	}()
	return _d.Speak.SayHello(ctx, name)
}

type MoveWithTracing struct {
	_sourceGlobal.Move
	_cfg tracing.TracingConfig
}

// NewMoveWithTracing returns MoveWithTracing
func NewMoveWithTracing(base _sourceGlobal.Move, opts ...tracing.TracingOption) MoveWithTracing {
	return MoveWithTracing{
		Move: base,
		_cfg: tracing.NewTracingConfig(opts...),
	}
}

// Walk implements Move
func (_d MoveWithTracing) Walk(ctx context.Context, distance int) (s1 string) {
	span, ctx := _d._cfg.StartSpan(ctx, "Move.Walk")
	defer func() {
		_d._cfg.FinishSpan(span, nil, map[string]interface{}{
			"ctx":      ctx,
			"distance": distance}, map[string]interface{}{
			"s1": s1})
	}()
	return _d.Move.Walk(ctx, distance)
}
